---
platform: linux
image_resource:
  type: docker-image
  source: {repository: ghcr.io/cloudfoundry/bosh/gcscli}
inputs:
- name: gcscli-src
  path: bosh-gcscli
- name: version-semver
outputs:
- name: out
run:
  path: bosh-gcscli/ci/tasks/build.sh
params:
  GOOS: linux
