---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/bosh-gcscli}
inputs:
- name: gcscli-src
  path: src/github.com/cloudfoundry/bosh-gcscli
- name: version-semver
outputs:
- name: out
run:
  path: src/github.com/cloudfoundry/bosh-gcscli/ci/tasks/build.sh
params:
  GOOS: linux