---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/bosh-gcscli}
inputs:
- name: gcscli-src
  path: bosh-gcscli
run:
  path: bosh-gcscli/ci/tasks/run-fast-int.sh
params:
  google_project: replace-me
  google_json_key_data: |
    replace-me
