---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/gce-cpi-release}
inputs:
- name: gcscli-src
  path: src/github.com/cloudfoundry/bosh-gcscli
run:
  path: src/github.com/cloudfoundry/bosh-gcscli/ci/tasks/run-int.sh
params:
  google_json_key_data: |
    replace-me