jobs:
  - name: run-unit-develop
    plan:
    - trigger: true
      get: gcscli-src
      resource: bosh-gcscli-src-in-develop
    - get: bosh-gcscli-docker-image
      trigger: true

    - task: unit-tests
      image: bosh-gcscli-docker-image
      file: gcscli-src/ci/tasks/run-unit.yml

  - name: run-unit-main
    plan:
    - trigger: true
      get: gcscli-src
      resource: bosh-gcscli-src-in-main
      passed:
      - promote-develop
    - get: bosh-gcscli-docker-image
      trigger: true

    - task: unit-tests
      image: bosh-gcscli-docker-image
      file: gcscli-src/ci/tasks/run-unit.yml

  - name: run-fast-int-develop
    plan:
    - trigger: true
      get: gcscli-src
      resource: bosh-gcscli-src-in-develop
    - get: bosh-gcscli-docker-image
      trigger: true

    - task: fast-integration-tests
      image: bosh-gcscli-docker-image
      file: gcscli-src/ci/tasks/run-fast-int.yml
      params:
        google_json_key_data: ((gcp_service_key_json))

  - name: run-fast-int-main
    plan:
    - trigger: true
      get: gcscli-src
      resource: bosh-gcscli-src-in-main
      passed:
      - promote-develop
    - get: bosh-gcscli-docker-image
      trigger: true

    - task: fast-integration-tests
      image: bosh-gcscli-docker-image
      file: gcscli-src/ci/tasks/run-fast-int.yml
      params:
        google_json_key_data: ((gcp_service_key_json))

  - name: run-int-develop
    plan:
    - trigger: true
      get: gcscli-src
      resource: bosh-gcscli-src-in-develop
    - get: bosh-gcscli-docker-image
      trigger: true

    - task: full-integration-tests
      image: bosh-gcscli-docker-image
      file: gcscli-src/ci/tasks/run-int.yml
      params:
        google_json_key_data: ((gcp_service_key_json))

  - name: run-int-main
    plan:
    - trigger: true
      get: gcscli-src
      resource: bosh-gcscli-src-in-main
      passed:
      - promote-develop
    - get: bosh-gcscli-docker-image
      trigger: true

    - task: full-integration-tests
      image: bosh-gcscli-docker-image
      file: gcscli-src/ci/tasks/run-int.yml
      params:
        google_json_key_data: ((gcp_service_key_json))

  - name: promote-main
    plan:
    - in_parallel:
      - get: gcscli-src
        resource: bosh-gcscli-src-in-main
        trigger: true
        passed:
        - run-unit-main
        - run-fast-int-main
        - run-int-main
      - get: bosh-gcscli-docker-image
        trigger: true
        passed:
          - run-unit-main
          - run-fast-int-main
          - run-int-main

      - put: version-semver
        resource: version-semver-main
        params:
          bump: patch
    - in_parallel:
      - task: build-linux
        image: bosh-gcscli-docker-image
        file: gcscli-src/ci/tasks/build.yml
        output_mapping:
          out: out-linux
        params:
          GOOS: linux
      - task: build-windows
        image: bosh-gcscli-docker-image
        file: gcscli-src/ci/tasks/build.yml
        output_mapping:
          out: out-windows
        params:
          GOOS: windows
    - in_parallel:
      - put: release-bucket-linux
        resource: release-bucket-linux-main
        params:
          file: out-linux/bosh-gcscli-*-linux-amd64
      - put: release-bucket-windows
        resource: release-bucket-windows-main
        params:
          file: out-windows/bosh-gcscli-*-windows-amd64.exe
    - params:
        repository: gcscli-src
        tag: version-semver/number
        tag_prefix: v
      put: gcscli-src
      resource: bosh-gcscli-src-in-main

  - name: promote-develop
    plan:
    - get: gcscli-src
      resource: bosh-gcscli-src-in-develop
      trigger: true
      passed:
      - run-unit-develop
      - run-fast-int-develop
      - run-int-develop
    - put: gcs-cli
      resource: bosh-gcscli-src-in-main
      params:
        repository: gcscli-src

  - name: build-docker
    plan:
      - get: gcscli-src
        resource: bosh-gcscli-src-in-develop
      - get: bosh-golang-release-image
        trigger: true
      - put: bosh-gcscli-docker-image
        params:
          build: gcscli-src/ci/docker-image
          labels:
            org.opencontainers.image.source: https://github.com/cloudfoundry/bosh-gcscli

  - name: bump-deps
    plan:
    - in_parallel:
      - get: gcscli-src
        resource: bosh-gcscli-src-in-develop
      - get: golang-release
      - get: weekly
        trigger: true
      - get: bosh-gcscli-docker-image
    - task: bump-deps
      file: golang-release/ci/tasks/shared/bump-deps.yml
      image: bosh-gcscli-docker-image
      input_mapping:
        input_repo: gcscli-src
      output_mapping:
        output_repo: bumped-gcscli-src
    - task: unit-tests
      file: gcscli-src/ci/tasks/run-unit.yml
      image: bosh-gcscli-docker-image
      input_mapping:
        gcscli-src: bumped-gcscli-src
    - put: bosh-gcscli-src-in-develop
      params:
        repository: bumped-gcscli-src
        rebase: true

resource_types:
- name: semver
  type: docker-image
  source:
    repository: concourse/semver-resource
    tag: 1.6

resources:
  - name: bosh-gcscli-docker-image
    type: docker-image
    source:
      repository: ghcr.io/cloudfoundry/bosh/gcscli
      username: ((github_read_write_packages.username))
      password: ((github_read_write_packages.password))

  - name: bosh-golang-release-image
    type: docker-image
    source:
      repository: ghcr.io/cloudfoundry/bosh/golang-release
      username: ((github_read_write_packages.username))
      password: ((github_read_write_packages.password))

  - name: bosh-gcscli-src-in-develop
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh-gcscli.git
      branch: develop
      private_key: ((github_deploy_key_bosh-gcscli.private_key))

  - name: bosh-gcscli-src-in-main
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh-gcscli.git
      branch: main
      private_key: ((github_deploy_key_bosh-gcscli.private_key))

  - name: golang-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-package-golang-release.git

  - name: version-semver-main
    type: semver
    source:
      initial_version: 0.0.1
      key: current-version
      bucket: bosh-gcscli-artifacts
      access_key_id: ((bosh_gcscli_pipeline.username))
      secret_access_key: ((bosh_gcscli_pipeline.password))

  - name: release-bucket-linux-main
    type: s3
    source:
      regexp: bosh-gcscli-(.*)-linux-amd64
      bucket: bosh-gcscli-artifacts
      access_key_id: ((bosh_gcscli_pipeline.username))
      secret_access_key: ((bosh_gcscli_pipeline.password))

  - name: release-bucket-windows-main
    type: s3
    source:
      regexp: bosh-gcscli-(.*)-windows-amd64\.exe
      bucket: bosh-gcscli-artifacts
      access_key_id: ((bosh_gcscli_pipeline.username))
      secret_access_key: ((bosh_gcscli_pipeline.password))

  - name: weekly
    type: time
    source:
      start: 3:00 -0700
      stop: 4:30 -0700
      days: [ Saturday ]
