jobs:
  - name: run-unit-develop
    plan:
    - trigger: true
      get: gcscli-src
      resource: bosh-gcscli-src-in-develop

    - task: unit-tests
      file: gcscli-src/ci/tasks/run-unit.yml

  - name: run-unit-main
    plan:
    - trigger: true
      get: gcscli-src
      resource: bosh-gcscli-src-in-main
      passed:
      - promote-develop

    - task: unit-tests
      file: gcscli-src/ci/tasks/run-unit.yml

  - name: run-fast-int-develop
    plan:
    - trigger: true
      get: gcscli-src
      resource: bosh-gcscli-src-in-develop

    - task: fast-integration-tests
      file: gcscli-src/ci/tasks/run-fast-int.yml
      params:
        google_project: {{google_project}}
        google_json_key_data: {{google_json_key_data}}

  - name: run-fast-int-main
    plan:
    - trigger: true
      get: gcscli-src
      resource: bosh-gcscli-src-in-main
      passed:
      - promote-develop

    - task: fast-integration-tests
      file: gcscli-src/ci/tasks/run-fast-int.yml
      params:
        google_project: {{google_project}}
        google_json_key_data: {{google_json_key_data}}

  - name: run-int-develop
    plan:
    - trigger: true
      get: gcscli-src
      resource: bosh-gcscli-src-in-develop

    - task: full-integration-tests
      file: gcscli-src/ci/tasks/run-int.yml
      params:
        google_project: {{google_project}}
        google_json_key_data: {{google_json_key_data}}

  - name: run-int-main
    plan:
    - trigger: true
      get: gcscli-src
      resource: bosh-gcscli-src-in-main
      passed:
      - promote-develop

    - task: full-integration-tests
      file: gcscli-src/ci/tasks/run-int.yml
      params:
        google_project: {{google_project}}
        google_json_key_data: {{google_json_key_data}}

  - name: promote-main
    plan:
    - in_parallel:
      - get: gcscli-src
        resource: bosh-gcscli-src-in-main
        trigger: true
        passed:
        - run-unit-main
        - run-fast-int-main
        - run-int-main
      - put: version-semver
        resource: version-semver-main
        params:
          bump: patch
    - in_parallel:
      - task: build-linux
        file: gcscli-src/ci/tasks/build.yml
        output_mapping:
          out: out-linux
        params:
          GOOS: linux
      - task: build-windows
        file: gcscli-src/ci/tasks/build.yml
        output_mapping:
          out: out-windows
        params:
          GOOS: windows
    - in_parallel:
      - put: release-bucket-linux
        resource: release-bucket-linux-main
        params:
          file: out-linux/bosh-gcscli-*-linux-amd64
      - put: release-bucket-windows
        resource: release-bucket-windows-main
        params:
          file: out-windows/bosh-gcscli-*-windows-amd64.exe
    - params:
        repository: gcscli-src
        tag: version-semver/number
        tag_prefix: v
      put: gcscli-src
      resource: bosh-gcscli-src-in-main

  - name: promote-develop
    plan:
    - get: gcscli-src
      resource: bosh-gcscli-src-in-develop
      trigger: true
      passed:
      - run-unit-develop
      - run-fast-int-develop
      - run-int-develop
    - put: gcs-cli
      resource: bosh-gcscli-src-in-main
      params:
        repository: gcscli-src

  - name: build-docker
    plan:
      - get: gcscli-src
        resource: bosh-gcscli-src-in-develop
      - get: golang-release
        trigger: true
      - put: bosh-gcscli-dockerfile
        params:
          build: gcscli-src/ci/docker-image

  - name: bump-deps
    plan:
    - in_parallel:
      - get: gcscli-src
        resource: bosh-gcscli-src-in-develop
      - get: golang-release
      - get: weekly
        trigger: true
    - task: bump-deps
      file: golang-release/ci/tasks/shared/bump-deps.yml
      input_mapping:
        input_repo: gcscli-src
      output_mapping:
        output_repo: bumped-gcscli-src
    - task: unit-tests
      file: gcscli-src/ci/tasks/run-unit.yml
      input_mapping:
        gcscli-src: bumped-gcscli-src
    - put: bosh-gcscli-src-in-develop
      params:
        repository: bumped-gcscli-src
        rebase: true

resources:
  - name: bosh-gcscli-dockerfile
    type: docker-image
    source:
      repository: bosh/bosh-gcscli
      username: ((docker.username))
      password: ((docker.password))

  - name: bosh-gcscli-src-in-develop
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh-gcscli.git
      branch: develop
      private_key: ((gcscli_deploy_key))

  - name: bosh-gcscli-src-in-main
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh-gcscli.git
      branch: main
      private_key: ((gcscli_deploy_key))

  - name: golang-release
    type: git
    source:
      uri: https://github.com/bosh-packages/golang-release.git

  - name: version-semver-main
    type: semver
    source:
      initial_version: 0.0.1
      key: current-version
      bucket: {{gcscli_release_bucket}}
      access_key_id: {{gcscli_release_bucket_access_key}}
      secret_access_key: {{gcscli_release_bucket_secret_key}}

  - name: release-bucket-linux-main
    type: s3
    source:
      regexp: bosh-gcscli-(.*)-linux-amd64
      bucket: {{gcscli_release_bucket}}
      access_key_id: {{gcscli_release_bucket_access_key}}
      secret_access_key: {{gcscli_release_bucket_secret_key}}

  - name: release-bucket-windows-main
    type: s3
    source:
      regexp: bosh-gcscli-(.*)-windows-amd64\.exe
      bucket: {{gcscli_release_bucket}}
      access_key_id: {{gcscli_release_bucket_access_key}}
      secret_access_key: {{gcscli_release_bucket_secret_key}}

  - name: weekly
    type: time
    source:
      start: 3:00 -0700
      stop: 4:30 -0700
      days: [ Saturday ]
